/**
 * NewsFree365 — Curated Financial, Economic & Holiday Calendar Dataset
 *
 * Covers:
 * 1. Macroeconomic Events & Indicators (RBI, Fed, CPI, GDP, PMI, Trade)
 * 2. Stock Exchange & Bank Holidays (NSE, BSE, MCX, NYSE, NASDAQ)
 * 3. Corporate Quarterly Earnings / Results (Nifty 50, US Big Tech)
 */

export const ECONOMIC_EVENTS = [
  {
    id: 'eco-ecb-sep-2026',
    title: 'ECB Interest Rate Decision',
    category: 'interest_rate',
    country: 'EU',
    countryName: 'Eurozone',
    flag: '🇪🇺',
    authority: 'European Central Bank (ECB)',
    date: '2026-09-10',
    time: '12:15 GMT',
    impact: 'high',
    forecast: '3.25%',
    previous: '3.50%',
    actual: null,
    unit: '%',
  },
  {
    id: 'eco-in-iip-sep-2026',
    title: 'India Index of Industrial Production (IIP)',
    category: 'growth',
    country: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    authority: 'Ministry of Statistics (MoSPI)',
    date: '2026-09-11',
    time: '12:00 GMT',
    impact: 'medium',
    forecast: '4.8%',
    previous: '4.2%',
    actual: null,
    unit: '% YoY',
  },
  {
    id: 'eco-us-cpi-sep-2026',
    title: 'US Consumer Price Index (CPI)',
    category: 'inflation',
    country: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    authority: 'Bureau of Labor Statistics (BLS)',
    date: '2026-09-11',
    time: '12:30 GMT',
    impact: 'high',
    forecast: '2.5%',
    previous: '2.6%',
    actual: null,
    unit: '% YoY',
  },
  {
    id: 'eco-in-cpi-sep-2026',
    title: 'India Retail Inflation (CPI)',
    category: 'inflation',
    country: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    authority: 'MoSPI / Central Statistics Office',
    date: '2026-09-12',
    time: '12:00 GMT',
    impact: 'high',
    forecast: '3.65%',
    previous: '3.60%',
    actual: null,
    unit: '% YoY',
  },
  {
    id: 'eco-in-wpi-sep-2026',
    title: 'India Wholesale Price Index (WPI)',
    category: 'inflation',
    country: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    authority: 'Ministry of Commerce & Industry',
    date: '2026-09-14',
    time: '06:30 GMT',
    impact: 'medium',
    forecast: '1.85%',
    previous: '2.04%',
    actual: null,
    unit: '% YoY',
  },
  {
    id: 'eco-in-trade-sep-2026',
    title: 'India Merchandise Trade Balance',
    category: 'trade',
    country: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    authority: 'Ministry of Commerce',
    date: '2026-09-15',
    time: '11:00 GMT',
    impact: 'medium',
    forecast: '-$22.8B',
    previous: '-$23.5B',
    actual: null,
    unit: 'USD Billion',
  },
  {
    id: 'eco-fed-fomc-sep-2026',
    title: 'US Federal Reserve FOMC Rate Decision & Projections',
    category: 'interest_rate',
    country: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    authority: 'Federal Open Market Committee (FOMC)',
    date: '2026-09-16',
    time: '18:00 GMT',
    impact: 'high',
    forecast: '4.75% - 5.00%',
    previous: '5.00% - 5.25%',
    actual: null,
    unit: '%',
  },
  {
    id: 'eco-boe-sep-2026',
    title: 'Bank of England Official Bank Rate',
    category: 'interest_rate',
    country: 'UK',
    countryName: 'United Kingdom',
    flag: '🇬🇧',
    authority: 'Bank of England (BoE)',
    date: '2026-09-17',
    time: '11:00 GMT',
    impact: 'high',
    forecast: '4.75%',
    previous: '5.00%',
    actual: null,
    unit: '%',
  },
  {
    id: 'eco-us-gdp-sep-2026',
    title: 'US GDP Q2 Final / Annualized Growth',
    category: 'growth',
    country: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    authority: 'Bureau of Economic Analysis (BEA)',
    date: '2026-09-24',
    time: '12:30 GMT',
    impact: 'high',
    forecast: '3.0%',
    previous: '2.8%',
    actual: null,
    unit: '% QoQ Ann.',
  },
  {
    id: 'eco-global-pmi-oct-2026',
    title: 'Global Manufacturing & Services PMI Flash',
    category: 'pmi',
    country: 'GLOBAL',
    countryName: 'Global',
    flag: '🌐',
    authority: 'S&P Global',
    date: '2026-10-01',
    time: '04:30 GMT',
    impact: 'medium',
    forecast: '52.4',
    previous: '51.8',
    actual: null,
    unit: 'Index Points',
  },
  {
    id: 'eco-rbi-mpc-oct-2026',
    title: 'RBI Monetary Policy Committee (MPC) Rate Decision',
    category: 'interest_rate',
    country: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    authority: 'Reserve Bank of India (RBI)',
    date: '2026-10-08',
    time: '04:30 GMT',
    impact: 'high',
    forecast: '6.25%',
    previous: '6.50%',
    actual: null,
    unit: '%',
  },
  {
    id: 'eco-in-gdp-q2-nov-2026',
    title: 'India GDP Q2 (Jul - Sep) Official Release',
    category: 'growth',
    country: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    authority: 'National Statistical Office (NSO)',
    date: '2026-11-30',
    time: '12:00 GMT',
    impact: 'high',
    forecast: '6.9%',
    previous: '6.7%',
    actual: null,
    unit: '% YoY',
  },
  {
    id: 'eco-fed-fomc-dec-2026',
    title: 'US Federal Reserve FOMC Year-End Rate Decision',
    category: 'interest_rate',
    country: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    authority: 'Federal Reserve',
    date: '2026-12-16',
    time: '19:00 GMT',
    impact: 'high',
    forecast: '4.50% - 4.75%',
    previous: '4.75%',
    actual: null,
    unit: '%',
  },
];

export const MARKET_HOLIDAYS = [
  // ── India Market Holidays (NSE, BSE, MCX) 2026 ──────────────────────────
  {
    id: 'hol-in-independence-day-2026',
    name: 'Independence Day (India)',
    date: '2026-08-15',
    exchanges: ['NSE', 'BSE', 'MCX'],
    country: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    sessionStatus: 'Full Day Closed',
    isFullDayClose: true,
    impact: 'high',
    category: 'national',
  },
  {
    id: 'hol-id-e-milad-2026',
    name: 'Id-e-Milad (Milad-un-Nabi)',
    date: '2026-09-16',
    exchanges: ['NSE', 'BSE', 'MCX'],
    country: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    sessionStatus: 'Trading Closed (Morning); MCX Evening Open at 5:00 PM',
    isFullDayClose: false,
    impact: 'high',
    category: 'religious',
  },
  {
    id: 'hol-gandhi-jayanti-2026',
    name: 'Mahatma Gandhi Jayanti',
    date: '2026-10-02',
    exchanges: ['NSE', 'BSE', 'MCX', 'Banks'],
    country: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    sessionStatus: 'Full Day Closed (All Sessions)',
    isFullDayClose: true,
    impact: 'high',
    category: 'national',
  },
  {
    id: 'hol-dussehra-2026',
    name: 'Dussehra / Vijayadashami',
    date: '2026-10-20',
    exchanges: ['NSE', 'BSE', 'MCX'],
    country: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    sessionStatus: 'Full Day Closed',
    isFullDayClose: true,
    impact: 'high',
    category: 'festival',
  },
  {
    id: 'hol-diwali-muhurat-2026',
    name: 'Diwali (Laxmi Pujan) — Muhurat Trading',
    date: '2026-11-08',
    exchanges: ['NSE', 'BSE', 'MCX'],
    country: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    sessionStatus: 'Special 1-Hour Evening Trading Session (6:15 PM – 7:15 PM)',
    isFullDayClose: false,
    impact: 'high',
    category: 'festival',
  },
  {
    id: 'hol-diwali-balipratipada-2026',
    name: 'Diwali Balipratipada',
    date: '2026-11-10',
    exchanges: ['NSE', 'BSE', 'MCX'],
    country: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    sessionStatus: 'Full Day Closed',
    isFullDayClose: true,
    impact: 'high',
    category: 'festival',
  },
  {
    id: 'hol-guru-nanak-2026',
    name: 'Guru Nanak Jayanti',
    date: '2026-11-24',
    exchanges: ['NSE', 'BSE', 'MCX'],
    country: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    sessionStatus: 'Full Day Closed',
    isFullDayClose: true,
    impact: 'high',
    category: 'religious',
  },

  // ── US Market Holidays (NYSE, NASDAQ) 2026 ──────────────────────────────
  {
    id: 'hol-us-labor-day-2026',
    name: 'US Labor Day',
    date: '2026-09-07',
    exchanges: ['NYSE', 'NASDAQ'],
    country: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    sessionStatus: 'Full Day Closed',
    isFullDayClose: true,
    impact: 'high',
    category: 'national',
  },
  {
    id: 'hol-us-columbus-day-2026',
    name: 'Columbus Day / Indigenous Peoples’ Day',
    date: '2026-10-12',
    exchanges: ['SIFMA (Bond Markets)'],
    country: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    sessionStatus: 'US Bond Markets Closed; Stock Exchanges (NYSE, NASDAQ) Open',
    isFullDayClose: false,
    impact: 'medium',
    category: 'national',
  },
  {
    id: 'hol-us-veterans-day-2026',
    name: 'Veterans Day (US)',
    date: '2026-11-11',
    exchanges: ['SIFMA (Bond Markets)'],
    country: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    sessionStatus: 'US Bond Markets Closed; Stock Exchanges (NYSE, NASDAQ) Open',
    isFullDayClose: false,
    impact: 'medium',
    category: 'national',
  },
  {
    id: 'hol-us-thanksgiving-2026',
    name: 'Thanksgiving Day (US)',
    date: '2026-11-26',
    exchanges: ['NYSE', 'NASDAQ'],
    country: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    sessionStatus: 'Full Day Closed',
    isFullDayClose: true,
    impact: 'high',
    category: 'national',
  },
  {
    id: 'hol-us-black-friday-2026',
    name: 'Day After Thanksgiving (Black Friday)',
    date: '2026-11-27',
    exchanges: ['NYSE', 'NASDAQ'],
    country: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    sessionStatus: 'Early Market Close at 1:00 PM EST',
    isFullDayClose: false,
    impact: 'medium',
    category: 'national',
  },
  {
    id: 'hol-us-christmas-eve-2026',
    name: 'Christmas Eve (US)',
    date: '2026-12-24',
    exchanges: ['NYSE', 'NASDAQ'],
    country: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    sessionStatus: 'Early Market Close at 1:00 PM EST',
    isFullDayClose: false,
    impact: 'medium',
    category: 'festival',
  },

  // ── Global Year-End Holidays 2026-2027 ──────────────────────────────────
  {
    id: 'hol-christmas-2026',
    name: 'Christmas Day',
    date: '2026-12-25',
    exchanges: ['NSE', 'BSE', 'MCX', 'NYSE', 'NASDAQ', 'LSE'],
    country: 'GLOBAL',
    countryName: 'Global Markets',
    flag: '🌐',
    sessionStatus: 'Global Exchanges Closed',
    isFullDayClose: true,
    impact: 'high',
    category: 'international',
  },
  {
    id: 'hol-new-year-2027',
    name: 'New Year’s Day 2027',
    date: '2027-01-01',
    exchanges: ['NYSE', 'NASDAQ', 'LSE', 'Tokyo', 'NSE', 'BSE'],
    country: 'GLOBAL',
    countryName: 'Global Markets',
    flag: '🌐',
    sessionStatus: 'Global Markets Closed',
    isFullDayClose: true,
    impact: 'high',
    category: 'international',
  },

  // ── US Market Holidays (NYSE, NASDAQ) 2027 ──────────────────────────────
  {
    id: 'hol-us-mlk-day-2027',
    name: 'Martin Luther King Jr. Day',
    date: '2027-01-18',
    exchanges: ['NYSE', 'NASDAQ'],
    country: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    sessionStatus: 'Full Day Closed',
    isFullDayClose: true,
    impact: 'high',
    category: 'national',
  },
  {
    id: 'hol-us-presidents-day-2027',
    name: 'Washington’s Birthday (Presidents’ Day)',
    date: '2027-02-15',
    exchanges: ['NYSE', 'NASDAQ'],
    country: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    sessionStatus: 'Full Day Closed',
    isFullDayClose: true,
    impact: 'high',
    category: 'national',
  },
  {
    id: 'hol-us-good-friday-2027',
    name: 'Good Friday (US)',
    date: '2027-03-26',
    exchanges: ['NYSE', 'NASDAQ'],
    country: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    sessionStatus: 'Full Day Closed',
    isFullDayClose: true,
    impact: 'high',
    category: 'religious',
  },
  {
    id: 'hol-us-memorial-day-2027',
    name: 'Memorial Day (US)',
    date: '2027-05-31',
    exchanges: ['NYSE', 'NASDAQ'],
    country: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    sessionStatus: 'Full Day Closed',
    isFullDayClose: true,
    impact: 'high',
    category: 'national',
  },
  {
    id: 'hol-us-juneteenth-2027',
    name: 'Juneteenth National Independence Day (Observed)',
    date: '2027-06-18',
    exchanges: ['NYSE', 'NASDAQ'],
    country: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    sessionStatus: 'Full Day Closed',
    isFullDayClose: true,
    impact: 'high',
    category: 'national',
  },
  {
    id: 'hol-us-independence-day-2027',
    name: 'Independence Day (Observed)',
    date: '2027-07-05',
    exchanges: ['NYSE', 'NASDAQ'],
    country: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    sessionStatus: 'Full Day Closed',
    isFullDayClose: true,
    impact: 'high',
    category: 'national',
  },

  // ── India Market Holidays (NSE, BSE, MCX) 2027 ──────────────────────────
  {
    id: 'hol-republic-day-2027',
    name: 'Republic Day (India)',
    date: '2027-01-26',
    exchanges: ['NSE', 'BSE', 'MCX', 'Banks'],
    country: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    sessionStatus: 'Full Day Closed',
    isFullDayClose: true,
    impact: 'high',
    category: 'national',
  },
  {
    id: 'hol-in-mahashivratri-2027',
    name: 'Mahashivratri',
    date: '2027-02-15',
    exchanges: ['NSE', 'BSE', 'MCX'],
    country: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    sessionStatus: 'Full Day Closed',
    isFullDayClose: true,
    impact: 'high',
    category: 'religious',
  },
  {
    id: 'hol-in-holi-2027',
    name: 'Holi',
    date: '2027-03-24',
    exchanges: ['NSE', 'BSE', 'MCX'],
    country: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    sessionStatus: 'Full Day Closed',
    isFullDayClose: true,
    impact: 'high',
    category: 'festival',
  },
  {
    id: 'hol-in-good-friday-2027',
    name: 'Good Friday (India)',
    date: '2027-03-26',
    exchanges: ['NSE', 'BSE', 'MCX'],
    country: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    sessionStatus: 'Full Day Closed',
    isFullDayClose: true,
    impact: 'high',
    category: 'religious',
  },
  {
    id: 'hol-in-ambedkar-jayanti-2027',
    name: 'Dr. Baba Saheb Ambedkar Jayanti',
    date: '2027-04-14',
    exchanges: ['NSE', 'BSE', 'MCX'],
    country: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    sessionStatus: 'Full Day Closed',
    isFullDayClose: true,
    impact: 'high',
    category: 'national',
  },
  {
    id: 'hol-in-maharashtra-day-2027',
    name: 'Maharashtra Day',
    date: '2027-05-01',
    exchanges: ['NSE', 'BSE', 'MCX'],
    country: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    sessionStatus: 'Full Day Closed',
    isFullDayClose: true,
    impact: 'high',
    category: 'national',
  },
  {
    id: 'hol-in-bakri-id-2027',
    name: 'Bakri Id / Eid-ul-Adha',
    date: '2027-05-17',
    exchanges: ['NSE', 'BSE', 'MCX'],
    country: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    sessionStatus: 'Full Day Closed',
    isFullDayClose: true,
    impact: 'high',
    category: 'religious',
  },
  {
    id: 'hol-in-muharram-2027',
    name: 'Muharram',
    date: '2027-06-16',
    exchanges: ['NSE', 'BSE', 'MCX'],
    country: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    sessionStatus: 'Full Day Closed',
    isFullDayClose: true,
    impact: 'high',
    category: 'religious',
  },
  {
    id: 'hol-in-independence-day-2027',
    name: 'Independence Day 2027 (India)',
    date: '2027-08-15',
    exchanges: ['NSE', 'BSE', 'MCX'],
    country: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    sessionStatus: 'Full Day Closed',
    isFullDayClose: true,
    impact: 'high',
    category: 'national',
  },
];

export const CORPORATE_RESULTS = [];
export const IPO_EVENTS = [];
export const DIVIDEND_EVENTS = [];

export const COMMODITY_EVENTS = [
  {
    id: 'com-opec-oct-2026',
    title: 'OPEC+ Joint Ministerial Monitoring Meeting (JMMC)',
    commodity: 'Crude Oil (Brent / WTI)',
    authority: 'OPEC Secretariat (Vienna)',
    country: 'GLOBAL',
    countryName: 'Global Markets',
    flag: '🛢️',
    date: '2026-10-02',
    time: '11:00 GMT',
    impact: 'high',
    forecast: 'Production Freeze Extension',
    previous: '2.2 mb/d Voluntary Cuts',
  },
  {
    id: 'com-eia-crude-sep-2026',
    title: 'US EIA Weekly Petroleum Status Report',
    commodity: 'Crude Oil & Gasoline',
    authority: 'Energy Information Administration (EIA)',
    country: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    date: '2026-09-16',
    time: '14:30 GMT',
    impact: 'high',
    forecast: '-1.8M Barrels',
    previous: '-2.4M Barrels',
  },
  {
    id: 'com-mcx-gold-oct-2026',
    title: 'MCX Gold & Silver Contract Expiry & Delivery',
    commodity: 'Precious Metals (Gold / Silver)',
    authority: 'Multi Commodity Exchange (MCX)',
    country: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    date: '2026-10-05',
    time: '23:30 IST',
    impact: 'medium',
    forecast: 'Physical Delivery Phase',
    previous: 'Rolling Settlement',
  },
];

