/**
 * Symbols for GET /api/market-quotes (Yahoo Finance chart API).
 * sectionId groups the UI (country / region). country is the full name shown on each card.
 */
export const MARKET_QUOTE_ROWS = [
  {
    id: 'gspc',
    symbol: '^GSPC',
    label: 'S&P 500',
    group: 'US',
    sectionId: 'us',
    country: 'United States',
  },
  {
    id: 'dji',
    symbol: '^DJI',
    label: 'Dow Jones',
    group: 'US',
    sectionId: 'us',
    country: 'United States',
  },
  {
    id: 'ixic',
    symbol: '^IXIC',
    label: 'Nasdaq Composite',
    group: 'US',
    sectionId: 'us',
    country: 'United States',
  },
  {
    id: 'vix',
    symbol: '^VIX',
    label: 'VIX',
    group: 'US',
    sectionId: 'us',
    country: 'United States',
  },
  {
    id: 'nsei',
    symbol: '^NSEI',
    label: 'Nifty 50',
    group: 'India',
    sectionId: 'india',
    country: 'India',
  },
  {
    id: 'bsesn',
    symbol: '^BSESN',
    label: 'BSE Sensex',
    group: 'India',
    sectionId: 'india',
    country: 'India',
  },
  {
    id: 'sse',
    symbol: '000001.SS',
    label: 'Shanghai Composite',
    group: 'China',
    sectionId: 'china',
    country: 'China',
  },
  {
    id: 'ftse',
    symbol: '^FTSE',
    label: 'FTSE 100',
    group: 'Global',
    sectionId: 'united_kingdom',
    country: 'United Kingdom',
  },
  {
    id: 'n225',
    symbol: '^N225',
    label: 'Nikkei 225',
    group: 'Global',
    sectionId: 'japan',
    country: 'Japan',
  },
  {
    id: 'gdaxi',
    symbol: '^GDAXI',
    label: 'DAX',
    group: 'Global',
    sectionId: 'germany',
    country: 'Germany',
  },
  {
    id: 'cl',
    symbol: 'CL=F',
    label: 'WTI crude',
    group: 'Commodities',
    sectionId: 'commodities',
    country: 'Global (NYMEX)',
  },
  {
    id: 'gc',
    symbol: 'GC=F',
    label: 'Gold',
    group: 'Commodities',
    sectionId: 'commodities',
    country: 'Global (COMEX)',
  },
  {
    id: 'bz',
    symbol: 'BZ=F',
    label: 'Brent crude',
    group: 'Commodities',
    sectionId: 'commodities',
    country: 'Global (ICE)',
  },
  {
    id: 'usdinr',
    symbol: 'INR=X',
    label: 'USD / INR',
    group: 'FX',
    sectionId: 'fx',
    country: 'United States & India',
  },
  {
    id: 'btc',
    symbol: 'BTC-USD',
    label: 'Bitcoin',
    group: 'Crypto',
    sectionId: 'crypto',
    country: 'Global (spot, USD)',
  },
  {
    id: 'eth',
    symbol: 'ETH-USD',
    label: 'Ethereum',
    group: 'Crypto',
    sectionId: 'crypto',
    country: 'Global (spot, USD)',
  },
  {
    id: 'sol',
    symbol: 'SOL-USD',
    label: 'Solana',
    group: 'Crypto',
    sectionId: 'crypto',
    country: 'Global (spot, USD)',
  },
];
